let velocidad = 50
let tiempo_de_espera = 1500
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, velocidad)
basic.pause(velocidad)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, velocidad)
basic.pause(tiempo_de_espera)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, velocidad)
basic.pause(tiempo_de_espera)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, velocidad)
basic.pause(tiempo_de_espera)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, velocidad)
basic.pause(tiempo_de_espera)
maqueen.motorStop(maqueen.Motors.All)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, velocidad)
basic.pause(tiempo_de_espera)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, velocidad)
basic.pause(velocidad)
